sudo: required
dist: trusty
notifications:
  email: false
language: ruby
rvm:
  - 2.4.1
env:
  - RAILS_ENV=test
cache:
  bundler: true
services:
  - postgresql
addons:
  apt:
    packages:
    - xvfb
    - postgresql-9.6
    - postgresql-contrib-9.6
  postgresql: "9.6"
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - cp .env.example .env
  - bundle exec rails db:create
  - bundle exec rails db:structure:load
  - bundle exec rails db:seed
  - rake ci
  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
