sudo: required
dist: trusty
notifications:
  email: false
language: ruby
rvm:
  - 2.4.1
env:
  - RAILS_ENV=test
cache:
  bundler: true
services:
  - postgresql
addons:
  apt:
    packages:
    - postgresql-9.6
    - postgresql-contrib-9.6
  postgresql: "9.6"
before_script:
  - sudo service postgresql start
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - cp .env.example .env
  - bundle exec rails db:create
  - bundle exec rails db:structure:load
  - bundle exec rails db:seed
  - rake ci
  - CODECLIMATE_REPO_TOKEN=0a7c2a9ff76974762fbe7151d5e4aa171f8a86682672d0b32d52ae46b10b3f44 bundle exec codeclimate-test-reporter
