version: "1.{build}"

environment:
  matrix:
    - RUBY_VERSION: 24
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - git clone https://github.com/codahale/bcrypt-ruby.git
  - cd bcrypt-ruby
  - gem build bcrypt.gemspec
  - gem install gem-compiler
  - gem compile bcrypt-3.1.11.gem
  - gem install ./bcrypt-3.1.11-x86-mingw32.gem
  - cd ..
  - bundle install
build: off
services: postgresql
test_script:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - bundle exec rails db:create
  - bundle exec rails db:structure:load
  - bundle exec rails db:seed
  - set RAILS_ENV=test
  - set HEADLESS=on
  - CODECOV_TOKEN=e5f8d659-68e3-4dee-bbf7-96cda9a20a4d
  - bundle exec rake ci
