version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Install dependencies.
      - run: sudo apt-get update

      # Install Chrome.
      - run: wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P ~/
      - run: sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
      - run: sudo apt-get -f install -y
      - run: sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb

      # Install ChromeDriver.
      - run: wget -N http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip -P ~/
      - run: unzip ~/chromedriver_linux64.zip -d ~/
      - run: rm ~/chromedriver_linux64.zip
      - run: sudo mv -f ~/chromedriver /usr/local/share/
      - run: sudo chmod +x /usr/local/share/chromedriver
      - run: sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

      # Install Selenium.
      - run: wget -N http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar -P ~/
      - run: sudo mv -f ~/selenium-server-standalone-3.0.1.jar /usr/local/share/
      - run: sudo chmod +x /usr/local/share/selenium-server-standalone-3.0.1.jar
      - run: sudo ln -s /usr/local/share/selenium-server-standalone-3.0.1.jar /usr/local/bin/selenium-server-standalone-3.0.1.jar
      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:structure:load
            bundle exec rails db:seed
      - run:
          name: Parallel RSpec
          command: HEADLESS=on rake ci

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
